/* =====================================================================
   Prep Desk — Motivation Bank
   ---------------------------------------------------------------------
   300 quotes. Loaded BEFORE script.js.
   To add more, just append objects to the array below in the same
   format:  { text: "...", author: "..." }
   The no-repeat engine picks these up automatically — no other change
   needed anywhere in the app.
   ===================================================================== */

const MOTIVATION_QUOTES = [

  /* ---------- 1. Discipline & consistency ---------- */
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Unknown" },
  { text: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
  { text: "You do not rise to your goals; you fall to your systems.", author: "Unknown" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Unknown" },
  { text: "Consistency is what transforms average into excellence.", author: "Unknown" },
  { text: "The pain of discipline weighs ounces. The pain of regret weighs tons.", author: "Jim Rohn" },
  { text: "Do a little, every single day. That is the whole secret.", author: "Prep Desk" },
  { text: "Show up on the days you least feel like it. Those are the days that count.", author: "Prep Desk" },
  { text: "We are what we repeatedly do. Excellence, then, is a habit.", author: "Will Durant" },
  { text: "Rules kept only when convenient are not rules. They are moods.", author: "Prep Desk" },
  { text: "A bad day of studying still beats a perfect day of planning.", author: "Prep Desk" },
  { text: "The streak matters more than the session.", author: "Prep Desk" },
  { text: "Don't break the chain.", author: "Jerry Seinfeld" },
  { text: "Discipline is self-respect wearing work clothes.", author: "Prep Desk" },
  { text: "You will never regret the hour you studied. Only the one you skipped.", author: "Prep Desk" },
  { text: "Nothing is less productive than to make more efficient what should not be done at all.", author: "Peter Drucker" },
  { text: "Two hours daily beats fourteen hours on Sunday.", author: "Prep Desk" },
  { text: "Standards, not feelings, decide whether you open the book.", author: "Prep Desk" },
  { text: "The habit is the goal. The result is the by-product.", author: "Prep Desk" },
  { text: "Miss once, it's an accident. Miss twice, it's the new plan.", author: "Prep Desk" },
  { text: "Order and simplification are the first steps toward mastery.", author: "Thomas Mann" },
  { text: "How you spend your Tuesday is how you spend your life.", author: "Prep Desk" },
  { text: "The routine protects you on the days willpower doesn't show up.", author: "Prep Desk" },
  { text: "Slow is smooth, smooth is fast.", author: "Unknown" },
  { text: "You can't build a reputation on what you are going to do.", author: "Henry Ford" },
  { text: "Repetition is not boring. It is how skill is built.", author: "Prep Desk" },
  { text: "Half an hour, done daily, becomes a hundred and eighty hours a year.", author: "Prep Desk" },
  { text: "Your calendar tells the truth your intentions try to hide.", author: "Prep Desk" },
  { text: "Willpower is a battery. Habits are the wall socket.", author: "Prep Desk" },
  { text: "Excellence is boring at close range.", author: "Prep Desk" },

  /* ---------- 2. Starting & momentum ---------- */
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The best time to plant a tree was twenty years ago. The second best is now.", author: "Proverb" },
  { text: "Well begun is half done.", author: "Aristotle" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The first draft of anything is allowed to be bad.", author: "Prep Desk" },
  { text: "Waiting for the perfect moment is the most expensive habit you own.", author: "Prep Desk" },
  { text: "Action cures fear faster than thinking ever will.", author: "Prep Desk" },
  { text: "Begin, and the mind grows heated. Begin, and the work will be completed.", author: "Goethe" },
  { text: "Momentum is easier to steer than to create. So create it early.", author: "Prep Desk" },
  { text: "The hardest page is the one you haven't opened.", author: "Prep Desk" },
  { text: "Do the difficult things while they are easy.", author: "Lao Tzu" },
  { text: "Five minutes of work beats an hour of deciding to work.", author: "Prep Desk" },
  { text: "You can edit a bad page. You cannot edit a blank one.", author: "Jodi Picoult" },
  { text: "Ready is a decision, not a feeling.", author: "Prep Desk" },
  { text: "Everything you want is on the other side of the first hard hour.", author: "Prep Desk" },
  { text: "Don't wait for inspiration. It arrives while you work, not before.", author: "Prep Desk" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "The scariest moment is always just before you start.", author: "Stephen King" },
  { text: "Today is the youngest you will ever be. Use it.", author: "Prep Desk" },
  { text: "Amateurs wait for clarity. Professionals go looking for it.", author: "Prep Desk" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Open the book first. Motivation follows the page.", author: "Prep Desk" },
  { text: "A plan you began beats a plan you polished.", author: "Prep Desk" },
  { text: "Deciding is exhausting. Doing is energising.", author: "Prep Desk" },
  { text: "The distance between dreaming and doing is one uncomfortable minute.", author: "Prep Desk" },
  { text: "Do not despise small beginnings.", author: "Proverb" },
  { text: "Some starts are ugly. Ugly starts still count.", author: "Prep Desk" },
  { text: "The day you start is the day the clock starts working for you.", author: "Prep Desk" },

  /* ---------- 3. Failure & resilience ---------- */
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Every expert was once a beginner who refused to give up.", author: "Unknown" },
  { text: "A mock test is a diagnosis, not a verdict.", author: "Prep Desk" },
  { text: "You either win or you learn. There is no third outcome.", author: "Unknown" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "Failure is only the opportunity to begin again, more intelligently.", author: "Henry Ford" },
  { text: "Nobody remembers your attempt count. They remember your result.", author: "Prep Desk" },
  { text: "The score is feedback. Do not read it as identity.", author: "Prep Desk" },
  { text: "Fall down seven times and the eighth stand is the whole story.", author: "Prep Desk" },
  { text: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J. K. Rowling" },
  { text: "Being defeated is optional. Being knocked down is not.", author: "Unknown" },
  { text: "A bad attempt teaches more than an easy pass.", author: "Prep Desk" },
  { text: "Do not judge me by my success, judge me by how many times I got back up.", author: "Nelson Mandela" },
  { text: "The comeback is always stronger than the setback.", author: "Unknown" },
  { text: "Mistakes are tuition. Just make sure you attend the class.", author: "Prep Desk" },
  { text: "Bad marks are data. Panic is not.", author: "Prep Desk" },
  { text: "What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Losing a round is not losing the fight.", author: "Prep Desk" },
  { text: "Difficulties strengthen the mind, as labour does the body.", author: "Seneca" },
  { text: "The only real mistake is the one from which we learn nothing.", author: "Henry Ford" },
  { text: "Analyse the paper, not your worth.", author: "Prep Desk" },
  { text: "Resilience is just deciding, again, on a worse day.", author: "Prep Desk" },
  { text: "He who has a why to bear can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The bruise fades. The lesson stays.", author: "Prep Desk" },
  { text: "You are allowed a bad week. You are not allowed a bad decade.", author: "Prep Desk" },
  { text: "Storms make trees take deeper roots.", author: "Dolly Parton" },
  { text: "Recovering fast is a skill you can practise.", author: "Prep Desk" },
  { text: "The rejection letter is a redirection note.", author: "Prep Desk" },
  { text: "Keep going. Everything you need will arrive at the right chapter.", author: "Prep Desk" },

  /* ---------- 4. Focus & saying no ---------- */
  { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey" },
  { text: "You can do anything, but not everything.", author: "David Allen" },
  { text: "Focus is the art of knowing what to ignore.", author: "Prep Desk" },
  { text: "It is not daily increase but daily decrease that matters.", author: "Bruce Lee" },
  { text: "Beware the barrenness of a busy life.", author: "Socrates" },
  { text: "Ten open tabs is not research. It is avoidance with a scrollbar.", author: "Prep Desk" },
  { text: "Saying no to good things protects your yes for the great ones.", author: "Prep Desk" },
  { text: "The successful warrior is the average person with laser-like focus.", author: "Bruce Lee" },
  { text: "One syllabus, one page, one hour. That is the whole method.", author: "Prep Desk" },
  { text: "Concentrate all your thoughts upon the work at hand.", author: "Alexander Graham Bell" },
  { text: "Depth beats width when the exam gets hard.", author: "Prep Desk" },
  { text: "Half your distractions disappear the moment your phone leaves the room.", author: "Prep Desk" },
  { text: "If everything is a priority, nothing is.", author: "Unknown" },
  { text: "A wandering mind is an unhappy mind.", author: "Unknown" },
  { text: "Do fewer things, better.", author: "Prep Desk" },
  { text: "Your attention is the price of admission to any goal.", author: "Prep Desk" },
  { text: "Where attention goes, energy flows.", author: "Unknown" },
  { text: "Multitasking is just switching costs wearing a productivity costume.", author: "Prep Desk" },
  { text: "The chief danger in life is that you may take too many precautions.", author: "Alfred Adler" },
  { text: "Close the tab. Open the topic.", author: "Prep Desk" },
  { text: "A clear desk is a cheap upgrade to a clear mind.", author: "Prep Desk" },
  { text: "Absorb what is useful, discard what is useless.", author: "Bruce Lee" },
  { text: "Deep work is a competitive advantage precisely because it is rare.", author: "Prep Desk" },
  { text: "Guard your mornings. That is where the real hours live.", author: "Prep Desk" },
  { text: "Studying with notifications on is like reading in a crowd.", author: "Prep Desk" },
  { text: "The quality of your hour beats the quantity of your day.", author: "Prep Desk" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Do one topic completely before touching the second.", author: "Prep Desk" },
  { text: "Boredom is often just focus that hasn't warmed up yet.", author: "Prep Desk" },
  { text: "Protect the hour like it belongs to someone you love.", author: "Prep Desk" },

  /* ---------- 5. Learning & curiosity ---------- */
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The more I learn, the more I realise how much I don't know.", author: "Albert Einstein" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "If you can't explain it simply, you don't understand it well enough.", author: "Unknown" },
  { text: "Reading a chapter is not learning it. Recalling it is.", author: "Prep Desk" },
  { text: "Confusion is the sound of your understanding being rebuilt.", author: "Prep Desk" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Ask the dumb question early. It gets expensive later.", author: "Prep Desk" },
  { text: "Curiosity is the engine of achievement.", author: "Ken Robinson" },
  { text: "Highlighting feels like studying. Testing yourself actually is.", author: "Prep Desk" },
  { text: "The expert has failed more times than the beginner has tried.", author: "Unknown" },
  { text: "Revision is not repetition. It is retrieval.", author: "Prep Desk" },
  { text: "Wisdom begins in wonder.", author: "Socrates" },
  { text: "You learn the framework by using it, not by memorising it.", author: "Prep Desk" },
  { text: "Notes you never revisit are just handwriting practice.", author: "Prep Desk" },
  { text: "Learning is not attained by chance. It must be sought with ardour.", author: "Abigail Adams" },
  { text: "Teach the topic to an empty chair. The gaps will announce themselves.", author: "Prep Desk" },
  { text: "The illiterate of the future are those who cannot learn and relearn.", author: "Alvin Toffler" },
  { text: "Struggling with a concept is the fee for owning it.", author: "Prep Desk" },
  { text: "Read less, understand more.", author: "Prep Desk" },
  { text: "Anyone who stops learning is old, whether twenty or eighty.", author: "Henry Ford" },
  { text: "A framework is a lens, not a checklist.", author: "Prep Desk" },
  { text: "Take the hard course. Easy grades expire quickly.", author: "Prep Desk" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "Understand the why and the what becomes hard to forget.", author: "Prep Desk" },
  { text: "Every case you solve makes the next one shorter.", author: "Prep Desk" },
  { text: "Knowledge without application is a very expensive hobby.", author: "Prep Desk" },
  { text: "Change your opinions, keep your principles.", author: "Victor Hugo" },
  { text: "The best students are the ones still willing to be wrong.", author: "Prep Desk" },
  { text: "Learn the rules well, so you know how to break them properly.", author: "Dalai Lama" },

  /* ---------- 6. Confidence & self-belief ---------- */
  { text: "Confidence comes from preparation, not perfection.", author: "Unknown" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "You have been assigned this mountain to show others it can be moved.", author: "Mel Robbins" },
  { text: "Nervousness and excitement feel identical. Choose the better label.", author: "Prep Desk" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Speak like the person who did the work, because you did.", author: "Prep Desk" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "The room does not need you to be perfect. It needs you to be prepared.", author: "Prep Desk" },
  { text: "Argue for your limitations and, sure enough, they're yours.", author: "Richard Bach" },
  { text: "Confidence is a memory of past effort, not a personality trait.", author: "Prep Desk" },
  { text: "You miss every shot you talk yourself out of.", author: "Prep Desk" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Your only competition is the version of you from last month.", author: "Prep Desk" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "The imposter feeling shows up when you are exactly where you should be.", author: "Prep Desk" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Stop auditioning for approval you already earned.", author: "Prep Desk" },
  { text: "With confidence, you have won before you have started.", author: "Marcus Garvey" },
  { text: "Preparation is the loudest form of self-belief.", author: "Prep Desk" },
  { text: "You are braver than you believe and stronger than you seem.", author: "A. A. Milne" },
  { text: "Nobody in the interview room knows what you don't know.", author: "Prep Desk" },
  { text: "Own your answer. A confident wrong beats a mumbled right.", author: "Prep Desk" },
  { text: "It is not because things are difficult that we dare not venture.", author: "Seneca" },
  { text: "Talk to yourself the way you would to a friend who is trying hard.", author: "Prep Desk" },
  { text: "The quietest person in the room often has the best answer. Use your voice.", author: "Prep Desk" },
  { text: "Trust yourself. You know more than you think you do.", author: "Benjamin Spock" },
  { text: "Give yourself credit in public. You give it to everyone else.", author: "Prep Desk" },
  { text: "The seat at the table is not given. It is occupied.", author: "Prep Desk" },
  { text: "Walk in like you belong, because preparation bought you the ticket.", author: "Prep Desk" },

  /* ---------- 7. Time & priorities ---------- */
  { text: "Time is what we want most and what we use worst.", author: "William Penn" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "You will never find time for anything. You must make it.", author: "Charles Buxton" },
  { text: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler" },
  { text: "Busy is a choice. So is prepared.", author: "Prep Desk" },
  { text: "How we spend our days is how we spend our lives.", author: "Annie Dillard" },
  { text: "It is not that we have little time, but that we waste much of it.", author: "Seneca" },
  { text: "The evening scroll costs more than it charges.", author: "Prep Desk" },
  { text: "Until we can manage time, we can manage nothing else.", author: "Peter Drucker" },
  { text: "One year from today, you will wish you had started today.", author: "Prep Desk" },
  { text: "Do not count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "Deadlines are just goals with a spine.", author: "Prep Desk" },
  { text: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
  { text: "Nothing makes a study plan honest like a timer.", author: "Prep Desk" },
  { text: "Time you enjoy wasting is not wasted time — but know which is which.", author: "Prep Desk" },
  { text: "Ordinary people think merely of spending time. Great people think of using it.", author: "Arthur Schopenhauer" },
  { text: "The exam date is not moving. Your schedule can.", author: "Prep Desk" },
  { text: "Tomorrow is the busiest day of the week. Do not schedule things there.", author: "Prep Desk" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Postponing is a decision. It just doesn't feel like one.", author: "Prep Desk" },
  { text: "A month is thirty chances. You have already spent some.", author: "Prep Desk" },
  { text: "Take rest. A field that has rested gives a bountiful crop.", author: "Ovid" },
  { text: "Plan the week on Sunday and the week stops planning you.", author: "Prep Desk" },
  { text: "Urgency and importance are not the same word.", author: "Prep Desk" },
  { text: "Time is the coin of your life. Spend it yourself.", author: "Carl Sandburg" },
  { text: "Wasted mornings are the most expensive item on any student's budget.", author: "Prep Desk" },
  { text: "Sleep is not a reward for finishing. It is part of the method.", author: "Prep Desk" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
  { text: "Count backwards from the exam. Suddenly the plan writes itself.", author: "Prep Desk" },
  { text: "Someday is not a day of the week.", author: "Unknown" },

  /* ---------- 8. Hard work & craft ---------- */
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Talent is cheaper than table salt. Effort makes the difference.", author: "Stephen King" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Nothing worth having comes easy, and nothing easy is worth having.", author: "Unknown" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The hours nobody sees are the ones everybody notices later.", author: "Prep Desk" },
  { text: "Opportunity is missed because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "Do the work even when the applause is nowhere in sight.", author: "Prep Desk" },
  { text: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Sweat in preparation so you don't bleed in the exam hall.", author: "Prep Desk" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The grind is unglamorous, unphotogenic, and completely undefeated.", author: "Prep Desk" },
  { text: "Success usually comes to those too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Effort is the one variable entirely under your control.", author: "Prep Desk" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "The extra hour is where the rank lives.", author: "Prep Desk" },
  { text: "Perfection is not attainable, but chasing it, we catch excellence.", author: "Vince Lombardi" },
  { text: "There is no traffic jam on the extra mile.", author: "Roger Staubach" },
  { text: "Do it properly the first time or twice, badly, later.", author: "Prep Desk" },
  { text: "The dictionary is the only place success comes before work.", author: "Vince Lombardi" },
  { text: "Your competitors are studying right now. That is not a threat, it's a clock.", author: "Prep Desk" },
  { text: "Sow with your hand and not with the whole sack.", author: "Proverb" },
  { text: "Craft is what remains after the enthusiasm wears off.", author: "Prep Desk" },
  { text: "Persistence guarantees that results are inevitable.", author: "Paramahansa Yogananda" },
  { text: "Nobody has ever been promoted for the intensity of their intentions.", author: "Prep Desk" },
  { text: "Work like there is someone working twenty-four hours to take it away.", author: "Mark Cuban" },
  { text: "Effort compounds quietly and then all at once.", author: "Prep Desk" },
  { text: "Rest, but do not quit.", author: "Banksy" },

  /* ---------- 9. Growth & change ---------- */
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "Your future self is watching you right now through memories.", author: "Aubrey de Grey" },
  { text: "Growth and comfort do not coexist.", author: "Ginni Rometty" },
  { text: "If you are not uncomfortable, you are probably not growing.", author: "Prep Desk" },
  { text: "One percent better daily compounds into a different person.", author: "Prep Desk" },
  { text: "The only way out is through.", author: "Robert Frost" },
  { text: "You cannot swim for new horizons until you lose sight of the shore.", author: "William Faulkner" },
  { text: "What got you here will not get you there.", author: "Marshall Goldsmith" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am changing myself.", author: "Rumi" },
  { text: "The version of you that succeeds is currently being built by boring days.", author: "Prep Desk" },
  { text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsch" },
  { text: "Be not afraid of growing slowly; be afraid only of standing still.", author: "Chinese Proverb" },
  { text: "Outgrow your excuses before you outgrow your ambition.", author: "Prep Desk" },
  { text: "Continuous improvement beats delayed perfection.", author: "Mark Twain" },
  { text: "You are not behind. You are early in a long story.", author: "Prep Desk" },
  { text: "The oak fought the wind and broke. The willow bent and lived.", author: "Proverb" },
  { text: "Improvement is invisible day to day and obvious year to year.", author: "Prep Desk" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Upgrade your standards and the habits follow.", author: "Prep Desk" },
  { text: "The seed does not argue about the season. It just grows.", author: "Prep Desk" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy" },
  { text: "Old routines cannot carry new goals.", author: "Prep Desk" },
  { text: "Growth is uncomfortable because you have never been here before.", author: "Unknown" },
  { text: "Do not go where the path may lead. Go where there is no path.", author: "Ralph Waldo Emerson" },
  { text: "Measure progress against your start line, not someone else's finish.", author: "Prep Desk" },
  { text: "Bamboo spends four years in the soil and six weeks in the sky.", author: "Prep Desk" },
  { text: "What you resist, persists.", author: "Carl Jung" },
  { text: "Better a diamond with a flaw than a pebble without.", author: "Confucius" },
  { text: "You are allowed to become someone your old habits would not recognise.", author: "Prep Desk" },

  /* ---------- 10. Career, interviews & the MBA road ---------- */
  { text: "The case in front of you is just practice for the offer ahead of you.", author: "Prep Desk" },
  { text: "Structure your answer and half the interview is already won.", author: "Prep Desk" },
  { text: "Culture eats strategy for breakfast.", author: "Peter Drucker" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "In an interview, clarity is more persuasive than vocabulary.", author: "Prep Desk" },
  { text: "Marketing is not the art of selling. It is the art of being chosen.", author: "Prep Desk" },
  { text: "People do not buy what you do, they buy why you do it.", author: "Simon Sinek" },
  { text: "Hire character. Train skill.", author: "Peter Schutz" },
  { text: "The framework is your scaffolding, not your answer.", author: "Prep Desk" },
  { text: "Take care of your employees and they will take care of your business.", author: "Richard Branson" },
  { text: "A good question in an interview is worth three good answers.", author: "Prep Desk" },
  { text: "The customer's problem is the only brief that matters.", author: "Prep Desk" },
  { text: "Train people well enough so they can leave; treat them well enough so they don't.", author: "Richard Branson" },
  { text: "Numbers persuade rooms that stories opened.", author: "Prep Desk" },
  { text: "Your network is built by being useful, not by collecting contacts.", author: "Prep Desk" },
  { text: "The best marketing doesn't feel like marketing.", author: "Tom Fishburne" },
  { text: "Say the assumption out loud. Interviewers reward visible thinking.", author: "Prep Desk" },
  { text: "Great vision without great people is irrelevant.", author: "Jim Collins" },
  { text: "Every case has three parts: what, so what, now what.", author: "Prep Desk" },
  { text: "Leadership is not a title. It is what happens when nobody assigns it.", author: "Prep Desk" },
  { text: "The most important thing in communication is hearing what isn't said.", author: "Peter Drucker" },
  { text: "Practise the answer out loud. Your head is a generous grader.", author: "Prep Desk" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "The résumé opens the door. The preparation walks you through it.", author: "Prep Desk" },
  { text: "A brand is what people say about you when you are not in the room.", author: "Jeff Bezos" },
  { text: "Recruiters do not hire potential. They hire evidence.", author: "Prep Desk" },
  { text: "Strategy is choosing what not to do.", author: "Michael Porter" },
  { text: "Answer the question they asked before the one you prepared.", author: "Prep Desk" },
  { text: "Management is doing things right; leadership is doing the right things.", author: "Peter Drucker" },
  { text: "One day this whole grind becomes the story you tell in the interview.", author: "Prep Desk" }

];

// Expose to the app (works with plain <script> loading)
if (typeof window !== 'undefined') window.MOTIVATION_QUOTES = MOTIVATION_QUOTES;
